/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DigitalIDRegistry } from "./DigitalIDRegistry";
export * as factories from "./factories";
export { DigitalIDRegistry__factory } from "./factories/DigitalIDRegistry__factory";
